nlf_skeleton:
  ros__parameters:
    model_path: "nlf_s_multi.torchscript"
    model_url: "https://github.com/isarandi/nlf/releases/download/v0.3.2/nlf_s.torchscript"
    device: "cpu"
    conf_threshold: 0.3
    max_depth_m: 5.0
    imgsz: 416
    publish_mesh: true
    mesh_topic: "/human_pose/smpl_mesh"
    mesh_decimation: 4
    num_joints: 24
    process_every_n_frames: 5
